### ISSUE TITLE
Why you increase the image size to HxW and then use encode and decode mode?

### ISSUE THREAD

**Issue by Manolo1988** [jiangsutx/SPMC_VideoSR#15]
I wonder why you use encode and decode mode, as this will increase number of parameters. Have you tried to just output a H/2 x W/2 image after SPMC layer, and just generate a H x W image at the end of the model

**Comment by karenyun** [comment]
I think the reason is as the paper stated: the J(H) is sparse that the network needed to have large receptive fields to capture the image patterns and also make the feature map less sparse.

**Comment by jiangsutx** [comment]
As mentioned in the paper, we think we need to capture sub-pixel motion after SPMC layer.
If you still use smaller images (e.g. H/2 * W/2), that means it still waste the precision provided by MCT module. 
And the details in final HR images are just some regression result from network, rather than true information from motion between frames.

**Comment by karenyun** [comment]
hi, sorry to ask a naive question :-)
 I am reading some deep learning based papers,  and almost all methods used MC module to align two frames? Is the new warped frame more similar to the referenced frame? Does these will help the network to learn more spatial information or for what? 

And confused about why using H*W that will sufficiently use the precision from the MCT model? Sorry that I am just curious about the reasons! Thanks very much!

**Comment by jiangsutx** [comment]
Yes, according to our paper. Using this new warping method is better for super-resolution problem.

An intuitive example is that, when you calculate optical flow on Low-Resolution images, for example the flow value for pixel (1,1) is (1.12, 2.55). 
Then when we try enlarge to 4x, it indicates that this (1,1) pixel corresponds to ((1+1.12)*4, (1+2.55)*4) in the enlarged HR image. Ideally, all pixels in HR are likely to be pointed to. When you use normal warping or doing in LR space, you cannot do that.
