### ISSUE TITLE
能否给出real data 的链接？

### ISSUE THREAD

**Issue by HarukiYqM** [jiangsutx/SPMC_VideoSR#19]
能不能分享一下

**Comment by jiangsutx** [comment]
毕业之后有点找不到了。real data当时是用单反相机和iphone手机，拍摄远处的建筑、logo等细节丰富的物体。
之后在不改分辨率的情况下，直接crop出来每一帧的roi（利用了 TLD tracking出感兴趣的区域）。
https://www.cse.cuhk.edu.hk/leojia/projects/DeepSR/data/DeepSR_data.zip
这里有一些以前工作的real data，供参考。
