### ISSUE TITLE
Pixel shift in test dataset

### ISSUE THREAD

**Issue by ckkelvinchan** [jiangsutx/SPMC_VideoSR#22]
I found that there is a pixel shift between the low-resolution and high-resolution images. For instance, when I use MATLAB to upsample car05_001/input4/1000.png and compare with car05_001/truth/1000.png, I found that there is a non-negligible pixel shift. 

May I ask how do you compute the PSNR of bicubic interpolation?

**Comment by jiangsutx** [comment]
We consider the top-left pixel location as (0,0). 
When doing super-resolution, it will be enlarged to (0,0). 
This setting is consistent with many previous work, which contains a pixel shift compared to MATLAB and opencv.

I have just included a modified resize [here](https://github.com/jiangsutx/SPMC_VideoSR/blob/master/modules/srt_imresize.m)

**Comment by wwlCape** [comment]
@jiangsutx Hi, could you tell me how to crop a GT frame in order to match the SR result(640x480)? When I compute the PSNR, I find the result is very poor. Would you like to do me a favor?

**Comment by jiangsutx** [comment]
Sorry for the inconvenience for this size problem, caused by static graph of tensorflow.

In our demo code, we only process the top-left corner or input LR images. So you need to crop the top-left corner of the GT frame to calculate psnr.

We will rewrite the code and release pytorch version soon.

**Comment by wwlCape** [comment]
Thanks for replying. I certainly crop the corner of the GT frame, but get a poor PSNR value. the following is a part of the code for calculating the PSNR value. 
```
           for idx_im = 1:length(filepaths)
                %count = count + 1
                name_HR = filepaths(idx_im).name;
                name_SR = strrep(name_HR, 'HR', methods{idx_method});
                im_HR = imread(fullfile(HR_path, dataset{idx_set}, dataDir(i).name, name_HR));
                %%%SPMC
                im_HR = im_HR(1:480,1:640,:);
                im_SR = imread(fullfile(SR_path,  dataset{idx_set}, dataDir(i).name, name_SR));
                % change channel for evaluation
                % %%%%%%%%%%%%%%%%%%%%%%%change for RGB or YCbCr
                %compute in y channel
                if 3 == size(im_HR, 3)
                    im_HR_YCbCr = single(rgb2ycbcr(im2double(im_HR)));
                    im_HR_Y = im_HR_YCbCr(:,:,1);
                    im_SR_YCbCr = single(rgb2ycbcr(im2double(im_SR)));
                    im_SR_Y = im_SR_YCbCr(:,:,1);
                
                else
                    im_HR_Y = single(im2double(im_HR));
                    im_HR_Y = im_HR_Y(1:size(im_SR,1),1:size(im_SR,2),:);
                    im_SR_Y = single(im2double(im_SR));
                    
                end
                % calculate PSNR, SSIM
                [PSNR_all(idx_im), SSIM_all(idx_im)] = Cal_Y_PSNRSSIM(im_HR_Y*255, im_SR_Y*255, 0, 0);
                fprintf(results, 'x%d %d %s: PSNR= %f SSIM= %f\n', 4, idx_im, name_SR, PSNR_all(idx_im), SSIM_all(idx_im));
                fprintf('x%d %d %s: PSNR= %f SSIM= %f\n', 4, idx_im, name_SR, PSNR_all(idx_im), SSIM_all(idx_im));
            end

```
Can you give me some suggestions for getting accurate PSNR value? Thanks a lot!

**Comment by jiangsutx** [comment]
OK you use MATLAB psnr() function.

I remember that, this psnr() function will automatically decide max data range based on value type.
If your input image is float or double type, it will consider the max value is 1.0. If your input is uint8, it will consider max value as 255.

This max value will make great change to final results. I guess may be you can pass double-type image within range [0.0, 1.0] to test.

Moreover, you can also open output and GT images in two windows and overlap them. And then switch between these two images to see if they align well without any shift, as shifting will cause psnr to decrease very much.

**Comment by wwlCape** [comment]
OK, thank you so much. I will try these methods and give feedback.
