### ISSUE TITLE
update the link to the test dataset

### ISSUE THREAD

**Issue by ShihuaHuang95** [jiangsutx/SPMC_VideoSR#24]
Hi, all links you post at this project are void now, could you please update them? We want to test our video super-resolution method over the provided dataset.
By the way, many thanks for your contributions.

**Comment by jiangsutx** [comment]
I have tested the link and it works well for me.
https://research-1256631708.cos.ap-guangzhou.myqcloud.com/shared_files/spmc_videosr_test_set.zip

The files are hosted on Tencent cloud. It should be ok for both mainland China and abroad.

**Comment by ShihuaHuang95** [comment]
Oh, yes, this link works now! Many thanks! Pre-happy new year!
