### ISSUE TITLE
About the testing set of SPMCS

### ISSUE THREAD

**Issue by littlewhitesea** [jiangsutx/SPMC_VideoSR#27]
Thanks for your excellent work.

The link to the testing set of SPMCS could not be opened. Could you release the testing set again?

**Comment by jiangsutx** [comment]
I think I have fixed that problem now.
Please try that link again and check if it works.

Sorry for the trouble.

**Comment by littlewhitesea** [comment]
Thanks, I have  successfully downloaded the testing set.
