### ISSUE TITLE
Multi-frames ConvLSTM problem

### ISSUE THREAD

**Issue by Zhanlgu** [jiangsutx/SPMC_VideoSR#7]
Hi! I have some problem of your model using ConvLSTM. When handling the 3-frames SR, the model uses just one ConvLSTM or two? Could you show us more details of the model? Thank you~

**Comment by jiangsutx** [comment]
We use one ConvLSTM. 
And for 3-frame setting, first, 0-th frame goes into the network: encoder - convlstm - decoder.
Second, 1-th frame goes into the network: encoder - convlstm - decoder. And this time convlstm also takes hidden state from previous time step as input.
Hope this answers your question.

**Comment by Zhanlgu** [comment]
Hi,

Does that mean the encoder-convlstm-decoder share the weights when processing the 0-th and 1-th frames?  Since I read your code and found there are two convlstms that have different names, I thought you used different convlstms for different frames.

**Comment by jiangsutx** [comment]
Yes, they are sharing the weights.

**Comment by Zhanlgu** [comment]
Thanks for reply.
